version: '2'
services:
#ERP
  web:
    image: odoo:11.0
    depends_on:
      - mydb
    ports:
      - "80:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
  mydb:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
    volumes:
      - my-datavolume:/var/lib/postgresql
  
volumes:
#ERP
  my-datavolume:
    driver: local

 