version: '2'
services:
#ERP
  web:
    image: odoo:12.0
    depends_on:
      - mydb
    ports:
      - "80:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=myodoo
    
  mydb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=odoo
      - MYSQL_ROOT_PASSWORD = myodoo
      - MARIADB_DATABASE=postgres
      - ALLOW_EMPTY_PASSWORD=yes
      - SUITECRM_USERNAME=user
      - SUITECRM_PASSWORD=bitnami 
 